model:
  name: "mistral-community/pixtral-12b"
  repo_id: "pixtral-12b-casters"
  output_dir: "pixtral-12b-casters"

training:
  num_train_epochs: 3
  per_device_batch_size: 2
  learning_rate: 0.0002
  gradient_accumulation_steps: 3
  gradient_checkpointing: true
  gradient_checkpointing_steps: 3
  warmup_ratio: 0.1
  weight_decay: 0.1
  max_grad_norm: 0.5
  fp16: true
  tf32: false

lora:
  r: 16
  lora_alpha: 16
  lora_dropout: 0.1
  target_modules: ["q_proj", "v_proj"]
  bias: "none"
  task_type: "CAUSAL_LM"

logging:
  logging_steps: 10
  save_steps: 20
  project_name: "tcg-fm"
  run_name: "pixtral-12b-casters"

data:
  train_file: "data/processed/casters_cards.jsonl" 